version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  end-to-end-tests:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest tests/end-to-end

workflows:
  end-to-end-tests:
    jobs:
      - end-to-end-tests
